#!/usr/bin/env python3
"""Unit tests for lsh_index.py -- the pure hashing/pairing functions in
isolation, plus a small end-to-end pass through sync_index()/
scan_candidate_pairs() against a real (temp-file) SQLite DB, since WAL mode
(db.py) needs a real file, not :memory:."""

import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np

import db  # noqa: E402
import lsh_index  # noqa: E402


class TestBucketKeys(unittest.TestCase):
    def test_shape(self):
        rng = np.random.default_rng(0)
        vectors = rng.standard_normal((5, 8)).astype(np.float32)
        planes = rng.standard_normal((3, 4, 8)).astype(np.float32)  # 3 tables, 4 bits, dim=8
        keys = lsh_index.bucket_keys(vectors, planes)
        self.assertEqual(keys.shape, (5, 3))
        self.assertEqual(keys.dtype, np.int64)

    def test_identical_vectors_get_identical_keys(self):
        rng = np.random.default_rng(1)
        v = rng.standard_normal((1, 16)).astype(np.float32)
        vectors = np.vstack([v, v, v])
        planes = rng.standard_normal((4, 6, 16)).astype(np.float32)
        keys = lsh_index.bucket_keys(vectors, planes)
        self.assertTrue((keys[0] == keys[1]).all())
        self.assertTrue((keys[1] == keys[2]).all())

    def test_opposite_vectors_get_complementary_keys(self):
        # v and -v land on opposite sides of every hyperplane through the origin,
        # so their k-bit codes should be exact bitwise complements (within k bits).
        rng = np.random.default_rng(2)
        v = rng.standard_normal((1, 10)).astype(np.float32)
        vectors = np.vstack([v, -v])
        bits_per_table = 5
        planes = rng.standard_normal((2, bits_per_table, 10)).astype(np.float32)
        # Avoid the zero-projection edge case (>=0 counts a tie as "same side") by
        # regenerating any plane that lands exactly on the hyperplane -- vanishingly
        # unlikely with continuous random data, but keeps the test deterministic.
        keys = lsh_index.bucket_keys(vectors, planes)
        full_mask = (1 << bits_per_table) - 1
        for table in range(planes.shape[0]):
            self.assertEqual(keys[0, table] ^ keys[1, table], full_mask)

    def test_known_hyperplane_split(self):
        # Single table, single bit: one hyperplane normal to the x-axis. Vectors with
        # positive x project >=0 (bit=1), negative x project <0 (bit=0).
        vectors = np.array([[1.0, 0.0], [-1.0, 0.0], [0.5, 100.0]], dtype=np.float32)
        planes = np.array([[[1.0, 0.0]]], dtype=np.float32)  # (num_tables=1, bits=1, dim=2)
        keys = lsh_index.bucket_keys(vectors, planes)
        self.assertEqual(list(keys[:, 0]), [1, 0, 1])


class TestPairsForGroup(unittest.TestCase):
    def test_new_new_pairs_generated(self):
        pids = np.array([10, 20, 30], dtype=np.int64)
        is_new = np.array([True, True, True])
        pairs = lsh_index._pairs_for_group(pids, is_new)
        decoded = {(int(c >> 32), int(c & 0xFFFFFFFF)) for c in pairs}
        self.assertEqual(decoded, {(10, 20), (10, 30), (20, 30)})

    def test_old_old_pairs_excluded(self):
        # All old -- these were already generated by whichever earlier scan first
        # saw them co-occurring; re-emitting them here would be pure duplication.
        pids = np.array([10, 20, 30], dtype=np.int64)
        is_new = np.array([False, False, False])
        pairs = lsh_index._pairs_for_group(pids, is_new)
        self.assertEqual(len(pairs), 0)

    def test_new_old_pairs_generated_but_not_old_old(self):
        pids = np.array([1, 2, 3, 4], dtype=np.int64)
        is_new = np.array([True, False, False, True])  # ids 1 and 4 are new; 2, 3 are old
        pairs = lsh_index._pairs_for_group(pids, is_new)
        decoded = {(int(c >> 32), int(c & 0xFFFFFFFF)) for c in pairs}
        # new-new: (1,4); new-old: (1,2),(1,3),(2,4),(3,4). NOT (2,3) -- both old.
        self.assertEqual(decoded, {(1, 4), (1, 2), (1, 3), (2, 4), (3, 4)})

    def test_single_new_no_old_produces_nothing(self):
        pids = np.array([5], dtype=np.int64)
        is_new = np.array([True])
        pairs = lsh_index._pairs_for_group(pids, is_new)
        self.assertEqual(len(pairs), 0)


class TestSyncAndScanIntegration(unittest.TestCase):
    """Exercises sync_index()/scan_candidate_pairs() against a real temp-file
    library.sqlite3 with a minimal paragraphs table, to catch regressions
    that pure unit tests on bucket_keys()/_pairs_for_group() alone would miss
    (e.g. the incremental-scan bookkeeping, table wiring)."""

    def setUp(self):
        self.tmpdir = tempfile.TemporaryDirectory()
        self.db_path = Path(self.tmpdir.name) / "library.sqlite3"
        self.conn = db.connect(self.db_path)
        self.conn.executescript(
            """
            CREATE TABLE papers (id INTEGER PRIMARY KEY);
            CREATE TABLE paragraphs (
                id INTEGER PRIMARY KEY,
                paper_id INTEGER,
                para_index INTEGER,
                text TEXT,
                embedding BLOB,
                embedding_dim INTEGER,
                model TEXT
            );
            """
        )
        self.conn.commit()

    def tearDown(self):
        self.conn.close()
        self.tmpdir.cleanup()

    def _insert_paragraph(self, pid, vector):
        vector = np.asarray(vector, dtype=np.float32)
        self.conn.execute(
            "INSERT INTO paragraphs (id, paper_id, para_index, text, embedding, embedding_dim, model) "
            "VALUES (?, 1, 0, 'text', ?, ?, 'test-model')",
            (pid, vector.tobytes(), len(vector)),
        )
        self.conn.commit()

    def test_sync_index_is_idempotent(self):
        self._insert_paragraph(1, np.random.default_rng(0).standard_normal(8))
        _, n_indexed = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.assertEqual(n_indexed, 1)
        # Nothing new to index the second time.
        _, n_indexed_again = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.assertEqual(n_indexed_again, 0)

    def test_sync_index_id_chunking_covers_every_paragraph(self):
        """Regression test for the 2026-09-03 OOM (see todo.md): sync_index() now walks
        paragraph ids in id_chunk_size-wide ranges instead of one LEFT JOIN over the whole
        table. Uses a tiny id_chunk_size (2) against ids that deliberately straddle chunk
        boundaries -- including a gap (id 5 skipped) and a non-contiguous run -- to prove
        the chunking doesn't drop or double-count anything at the edges."""
        ids = [1, 2, 3, 4, 6, 7, 10]  # id 5 deliberately missing -- a real gap, not a bug
        for pid in ids:
            self._insert_paragraph(pid, np.random.default_rng(pid).standard_normal(8))
        _, n_indexed = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8, id_chunk_size=2)
        self.assertEqual(n_indexed, len(ids))
        indexed_ids = {
            r[0] for r in self.conn.execute(
                "SELECT DISTINCT paragraph_id FROM lsh_buckets WHERE table_num = 0"
            ).fetchall()
        }
        self.assertEqual(indexed_ids, set(ids))
        # Idempotent under chunking too -- a second call finds nothing new.
        _, n_indexed_again = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8, id_chunk_size=2)
        self.assertEqual(n_indexed_again, 0)

    def test_sync_index_migrates_preexisting_lsh_buckets_into_lsh_indexed(self):
        """Regression test for the second 2026-09-03 fix (see todo.md): checking "is this
        paragraph missing from lsh_buckets" directly OOM-killed a real run even chunked by
        id range, because lsh_buckets has up to num_tables rows per paragraph and stays
        huge regardless of chunking. sync_index() now tracks pending-ness in a dedicated
        lsh_indexed(paragraph_id) table instead. This simulates a database that already has
        real lsh_buckets rows from before lsh_indexed existed (inserted directly, bypassing
        sync_index()) -- the migration step must backfill lsh_indexed from them, NOT
        re-hash/re-insert into lsh_buckets a second time."""
        self._insert_paragraph(1, np.random.default_rng(1).standard_normal(8))
        self._insert_paragraph(2, np.random.default_rng(2).standard_normal(8))
        # Establish a real lsh_config row first -- otherwise load_or_create_planes() treats
        # the fake bucket rows inserted below as stale data under an undefined config and
        # wipes them on its normal first-time-setup path (correct behavior for the real
        # system; this test needs the config to already match, same as it always does by
        # the time a real sync_index() call would ever see pre-existing bucket rows).
        lsh_index.init_lsh_tables(self.conn)
        lsh_index.load_or_create_planes(self.conn, model="test-model", embedding_dim=8)
        # Simulate pre-existing lsh_buckets rows for paragraph 1 only (as if an earlier,
        # pre-lsh_indexed sync_index() run had already hashed it), with no lsh_indexed row.
        for table_num in range(lsh_index.DEFAULT_NUM_TABLES):
            self.conn.execute(
                "INSERT INTO lsh_buckets (table_num, bucket_key, paragraph_id) VALUES (?, 0, 1)", (table_num,)
            )
        self.conn.commit()
        pre_existing_bucket_rows = self.conn.execute(
            "SELECT COUNT(*) FROM lsh_buckets WHERE paragraph_id = 1"
        ).fetchone()[0]

        _, n_indexed = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8, id_chunk_size=1)

        # Only paragraph 2 (genuinely never indexed) should have been hashed this call.
        self.assertEqual(n_indexed, 1)
        indexed_ids = {r[0] for r in self.conn.execute("SELECT paragraph_id FROM lsh_indexed").fetchall()}
        self.assertEqual(indexed_ids, {1, 2})
        # Paragraph 1's pre-existing bucket rows must be untouched, not duplicated/re-derived.
        self.assertEqual(
            self.conn.execute("SELECT COUNT(*) FROM lsh_buckets WHERE paragraph_id = 1").fetchone()[0],
            pre_existing_bucket_rows,
        )

    def test_invalidate_paragraphs_clears_lsh_indexed_too(self):
        """A re-embedded paragraph (same id, new embedding) must be re-hashed, not skipped
        as already-indexed -- invalidate_paragraphs() has to clear lsh_indexed alongside
        lsh_buckets/lsh_scanned or sync_index() would never revisit it."""
        self._insert_paragraph(1, np.random.default_rng(1).standard_normal(8))
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.assertEqual(
            self.conn.execute("SELECT COUNT(*) FROM lsh_indexed WHERE paragraph_id = 1").fetchone()[0], 1
        )
        lsh_index.invalidate_paragraphs(self.conn, [1])
        self.assertEqual(
            self.conn.execute("SELECT COUNT(*) FROM lsh_indexed WHERE paragraph_id = 1").fetchone()[0], 0
        )
        # Re-embed at the same id, with a different vector -- must be re-indexed, not skipped.
        self.conn.execute(
            "UPDATE paragraphs SET embedding = ? WHERE id = 1",
            (np.random.default_rng(99).standard_normal(8).astype(np.float32).tobytes(),),
        )
        self.conn.commit()
        _, n_indexed = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.assertEqual(n_indexed, 1)

    def test_two_identical_vectors_become_candidates(self):
        vector = np.random.default_rng(1).standard_normal(8)
        self._insert_paragraph(1, vector)
        self._insert_paragraph(2, vector)  # exact duplicate embedding
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        pairs = lsh_index.scan_candidate_pairs(self.conn)
        self.assertIn((1, 2), pairs)

    def test_custom_max_candidate_pairs_raises_when_exceeded(self):
        """--max-candidate-pairs override (build_dupe_candidates.py) threads through
        to this exact check -- a caller that deliberately raises it past the
        module default takes on the memory cost knowingly; one that doesn't
        override still gets the conservative default."""
        vector = np.random.default_rng(3).standard_normal(8)
        for pid in (1, 2, 3):
            self._insert_paragraph(pid, vector)  # 3-way bucket -> C(3,2) = 3 pairs projected
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        with self.assertRaises(RuntimeError):
            lsh_index.scan_candidate_pairs(self.conn, max_candidate_pairs=2)

    def test_custom_max_candidate_pairs_allows_when_under(self):
        """3 identical vectors collide in the same bucket across all 16 tables --
        the pre-dedup projection sums per-table (16 x C(3,2) = 48), even though
        the final deduplicated result is just the 3 unique pairs; the ceiling
        must be sized against that projection, not the post-dedup count."""
        vector = np.random.default_rng(3).standard_normal(8)
        for pid in (1, 2, 3):
            self._insert_paragraph(pid, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        pairs = lsh_index.scan_candidate_pairs(self.conn, max_candidate_pairs=48)
        self.assertEqual(len(pairs), 3)

    def _create_staging_table(self):
        self.conn.execute(
            "CREATE TEMP TABLE staging (paragraph_id_lo INTEGER, paragraph_id_hi INTEGER, "
            "PRIMARY KEY (paragraph_id_lo, paragraph_id_hi))"
        )
        self.conn.commit()

    def test_scan_to_table_matches_in_memory_scan(self):
        """scan_candidate_pairs_to_table() must find exactly the same pairs as
        scan_candidate_pairs() -- it's a memory-bounded alternative Pass 2,
        not a different algorithm (see its docstring: added after a real OOM,
        todo.md 2026-08-26)."""
        vector = np.random.default_rng(4).standard_normal(8)
        for pid in (1, 2, 3, 4):
            self._insert_paragraph(pid, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        expected = lsh_index.scan_candidate_pairs(self.conn, max_candidate_pairs=10_000)

        # Fresh connection state for a clean incremental comparison: re-clear lsh_scanned
        # so scan_candidate_pairs_to_table() sees the same "everyone new" starting point.
        self.conn.execute("DELETE FROM lsh_scanned")
        self.conn.commit()
        self._create_staging_table()
        lsh_index.scan_candidate_pairs_to_table(self.conn, "staging", max_candidate_pairs=10_000)
        actual = set(self.conn.execute("SELECT paragraph_id_lo, paragraph_id_hi FROM staging").fetchall())
        self.assertEqual(actual, expected)

    def test_scan_to_table_batches_across_multiple_groups(self):
        """group_batch_size=1 forces every group into its own chunk -- the
        streamed result must still be complete and correctly deduplicated
        across chunk boundaries."""
        rng = np.random.default_rng(5)
        # Two separate duplicate pairs -> two separate bucket groups.
        v1 = rng.standard_normal(8)
        v2 = rng.standard_normal(8)
        self._insert_paragraph(1, v1)
        self._insert_paragraph(2, v1)
        self._insert_paragraph(3, v2)
        self._insert_paragraph(4, v2)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self._create_staging_table()
        n = lsh_index.scan_candidate_pairs_to_table(self.conn, "staging", group_batch_size=1)
        self.assertGreaterEqual(n, 2)
        actual = set(self.conn.execute("SELECT paragraph_id_lo, paragraph_id_hi FROM staging").fetchall())
        self.assertIn((1, 2), actual)
        self.assertIn((3, 4), actual)

    def test_scan_to_table_marks_scanned(self):
        """Incremental bookkeeping must still work -- a second call finds nothing new."""
        vector = np.random.default_rng(6).standard_normal(8)
        self._insert_paragraph(1, vector)
        self._insert_paragraph(2, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self._create_staging_table()
        first = lsh_index.scan_candidate_pairs_to_table(self.conn, "staging")
        self.assertGreater(first, 0)

        self.conn.execute("DELETE FROM staging")
        self.conn.commit()
        second = lsh_index.scan_candidate_pairs_to_table(self.conn, "staging")
        self.assertEqual(second, 0)

    def test_scan_to_table_respects_max_candidate_pairs(self):
        vector = np.random.default_rng(7).standard_normal(8)
        for pid in (1, 2, 3):
            self._insert_paragraph(pid, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self._create_staging_table()
        with self.assertRaises(RuntimeError):
            lsh_index.scan_candidate_pairs_to_table(self.conn, "staging", max_candidate_pairs=2)

    def test_incremental_scan_only_returns_new_pairs(self):
        rng = np.random.default_rng(2)
        vector = rng.standard_normal(8)
        self._insert_paragraph(1, vector)
        self._insert_paragraph(2, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        first_scan = lsh_index.scan_candidate_pairs(self.conn)
        self.assertIn((1, 2), first_scan)

        # Nothing new since -- incremental scan should return nothing more, even
        # though (1, 2) still objectively share a bucket.
        second_scan = lsh_index.scan_candidate_pairs(self.conn)
        self.assertEqual(second_scan, set())

        # Add a third identical-embedding paragraph -- only pairs touching the
        # new one (1,3) and (2,3) should come back, not (1,2) again.
        self._insert_paragraph(3, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        third_scan = lsh_index.scan_candidate_pairs(self.conn)
        self.assertEqual(third_scan, {(1, 3), (2, 3)})

    def test_full_rescan_reproduces_all_pairs(self):
        rng = np.random.default_rng(3)
        vector = rng.standard_normal(8)
        self._insert_paragraph(1, vector)
        self._insert_paragraph(2, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        lsh_index.scan_candidate_pairs(self.conn)  # first (incremental) scan, marks both scanned

        self._insert_paragraph(3, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        full = lsh_index.scan_candidate_pairs(self.conn, full_rescan=True)
        self.assertEqual(full, {(1, 2), (1, 3), (2, 3)})

    def test_orthogonal_vectors_unlikely_to_share_a_bucket(self):
        # Not a hard guarantee (LSH is probabilistic), but with num_tables=16 default
        # and clearly-dissimilar vectors, they shouldn't collide in this deterministic seed.
        self._insert_paragraph(1, [1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
        self._insert_paragraph(2, [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0])
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        pairs = lsh_index.scan_candidate_pairs(self.conn)
        self.assertNotIn((1, 2), pairs)

    def test_delete_orphaned_buckets_removes_missing_paragraph_rows(self):
        vector = np.random.default_rng(4).standard_normal(8)
        self._insert_paragraph(1, vector)
        self._insert_paragraph(2, vector)
        lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.conn.execute("DELETE FROM paragraphs WHERE id = 2")
        self.conn.commit()
        removed = lsh_index.delete_orphaned_buckets(self.conn)
        self.assertGreater(removed, 0)
        remaining = self.conn.execute(
            "SELECT COUNT(*) FROM lsh_buckets WHERE paragraph_id = 2"
        ).fetchone()[0]
        self.assertEqual(remaining, 0)

    def test_sync_index_indexes_every_paragraph_across_multiple_batches(self):
        """Regression test for the real OOM-kill incident: sync_index() used to
        fetchall() every pending paragraph's embedding in one shot before hashing
        it, which ballooned to 24.6GB RSS and got the whole process killed once
        the backlog reached ~2.5M paragraphs. The fix batches the read side too
        (batch_size=2000, see sync_index()'s own comment) -- this inserts more
        than one batch's worth of paragraphs and checks none are lost at a batch
        boundary and none are double-counted."""
        count = 4500  # > 2 x the 2000-per-batch size, to cross two batch boundaries
        rng = np.random.default_rng(5)
        for pid in range(1, count + 1):
            self._insert_paragraph(pid, rng.standard_normal(8))
        _, n_indexed = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.assertEqual(n_indexed, count)

        indexed_ids = {
            r[0] for r in self.conn.execute(
                "SELECT DISTINCT paragraph_id FROM lsh_buckets WHERE table_num = 0"
            ).fetchall()
        }
        self.assertEqual(indexed_ids, set(range(1, count + 1)))

        # Idempotent: nothing left to do on a second call.
        _, n_indexed_again = lsh_index.sync_index(self.conn, model="test-model", embedding_dim=8)
        self.assertEqual(n_indexed_again, 0)


if __name__ == "__main__":
    unittest.main()
